---

name: Check

on: [push]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.4
    steps:
      - name: Login to github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: action/checkout@v2
      - name: Test
        run: docker-compose run --rm recipe_app sh -c "python manage.py test"
